# mkdocs.yml
site_name: Restorers

theme:
  name: material

plugins:
  - mkdocstrings

nav:
  - Home: 'index.md'
  - 'Models':
    - 'MirNetV2' : 'models/mirnetv2.md'
    - 'NAFNet': 'models/nafnet.md'
    - 'Zero-DCE': 'models/zero_dce_model.md'
  - 'Dataloader':
    - 'Base': 'dataloader/base.md'
  - 'Evaluation':
    - 'Base': 'evaluation/base.md'
    - 'LoLEvaluator': 'evaluation/lol_eval.md'
