[project]
name = "restorers"
version = "0.0.1"
description = "Image Restoration toolkit in TensorFlow"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "isort==5.10.1",
    "black==22.6.0",
    "pytest==7.1.2",
    "ml-collections==0.1.1",
    "pillow",
    "tqdm",
    "tensorflow-addons>=0.17.1",
    "transformers>=4.25.1",
    "wandb>=0.13.6"
]

# This is set automatically by flit using `etils.__version__`
dynamic = ["version"]

[project.urls]
homepage = "https://github.com/soumik12345/restorers"
repository = "https://github.com/soumik12345/restorers"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
