name: Documentation
on:
  push:
    branches:
      - main
      - saurav/add-auto-docs
      - deploy/docs
    paths:
      - .github/workflows/docs.yml
      - docs/**
      - mkdocs.yml

permissions:
  contents: write
  id-token: write

jobs:
  documentation:
    name: Update documentations on GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install .[docs]
      - run: mkdocs gh-deploy --force