name: Tests
on:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - restorers/**
      - pyproject.toml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  dataloader-tests:
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
    container: tensorflow/tensorflow
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -U pip
          pip install .[test]
          pytest -s restorers/tests/dataloader/
  
  model-tests:
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
    container: tensorflow/tensorflow
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -U pip
          pip install .[test]
          pytest -s restorers/tests/model/
  
  losses-tests:
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
    container: tensorflow/tensorflow
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -U pip
          pip install .[test]
          pytest -s restorers/tests/losses/
