name: Run tests
on:
  pull_request:
    paths:
      - .github/**
      - mirnetv2/**
      - tests.py
      - requirements.txt

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  run-tests:
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    container: tensorflow/tensorflow
    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1.0.1
      - run: |
          yes | apt install git
          pip install -U pip
          pip install git+https://github.com/soumik12345/mirnetv2.git@${BRANCH_NAME}
          pytest .
